import GoogleProvider from '../components/GoogleProvider'
import './globals.css'
import { Ubuntu } from 'next/font/google'
import Navbar from '../components/Navbar'
import MuiThemeProvider from '../components/MuiThemeProvider'
import Script from 'next/script'
import { cookies } from 'next/headers'
import Logo from '../app/assets/youtubelogo.png'
import Image from 'next/image'

export const ubuntu = Ubuntu({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata = {
  title: 'TubeSync',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const cookieStore = cookies();

  const isLoggedIn = JSON.parse(cookieStore.get('isLoggedIn')?.value);

  console.log(isLoggedIn);

  return (
    <html lang="en" className='bg-white'>

      <Script src="https://kit.fontawesome.com/c1677446e6.js" crossorigin="anonymous" />


      <body className={ubuntu.className}>
        {
          isLoggedIn ? <Navbar /> : <div className='text-center flex items-center absolute '>
            <Image
              src={Logo}
              width={80}
              height={80}
              alt="Picture of the author"
            />
            <div className='text-xl text-bold'>

              TubeSense
            </div>
          </div>
        }

        <MuiThemeProvider>
          <GoogleProvider>
            {children}
          </GoogleProvider>
        </MuiThemeProvider>

      </body>
    </html>
  )
}
