import GoogleProvider from '@/components/GoogleProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TubeSync',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en" className='bg-white'>
      <body className={inter.className}>

        <script src="https://media-editor.cloudinary.com/all.js" type="text/javascript"></script>


        <Navbar />
        <GoogleProvider>
          {children}
        </GoogleProvider>

      </body>
    </html>
  )
}
